# -*- coding: utf-8 -*-
"""Adjective clouds creation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hjI4UnVFOkLpC_Hpq1d-YpOpXolYw_r8
"""

#creating adjective clouds

import spacy

nlp = spacy.load("en_core_web_sm")
import numpy as np

import pandas as pd
ds=pd.read_csv("burgerking.csv")  #reading the comments csv file of particular phone
df=ds.iloc[:,:].values
df=np.array(df)
df=df.flatten()
l=[]
for i in df:
    doc = nlp(i)
    for token in doc:
        if  (token.pos_=="ADJ"):               #checking the words as adjectives
            l.append(token)
            
#converting data type from spacy.token to string
for i in range(0,len(l)):
    l[i]=str(l[i])

f=open("burgerking_adj.csv", "w+",encoding="UTF-8")             #opening files for saving cloud data
for i in l:
     f.write(i)
     f.write("\n")

     
f.close()