# -*- coding: utf-8 -*-
"""Timeline Tweets scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lC6j0vEE4zV60xsrPX7tIyFeZvn1f5rB
"""

import tweepy
import pandas as pd
import time

from twitterscraper import query_tweets
import datetime as dt
import pandas as pd
begin_date = dt.date(2020,4,1)
end_date = dt.date(2020,4,15)
limit = 1000
lang = 'English'

tweets = query_tweets("mcdonalds" , begindate = begin_date, enddate = end_date , limit = limit, lang = lang)

df = pd.DataFrame(t.__dict__ for t in tweets)
df.to_csv('mcdonalds_timeline.csv')